from dental_rag.agent.models import (
    AgentDecision,
    AgentIntent,
)
from dental_rag.llm.base import LLM


class AgentRouter:
    """
    Decide where a user query should be routed.
    """

    def __init__(
        self,
        llm: LLM,
    ) -> None:
        self.llm = llm

    def route(
        self,
        query: str,
    ) -> AgentDecision:
        if not query.strip():
            raise ValueError(
                "query cannot be blank",
            )

        prompt = self._build_prompt(
            query,
        )

        response = self.llm.generate(
            prompt,
        )

        return self._parse_response(
            response,
        )

    def _build_prompt(
        self,
        query: str,
    ) -> str:
        return f"""
You are a dental query router.

Classify the user question into one of these categories:

- clinic:
Questions about this specific dental clinic,
its services, doctors, working hours, prices,
appointments, policies, or internal documents.

- general_dental:
General dentistry questions,
medical explanations, symptoms, treatments,
or educational dental information.

Return only one word:
clinic
or
general_dental

User question:
{query}
""".strip()

    def _parse_response(
        self,
        response: str,
    ) -> AgentDecision:
        intent_value = response.strip().lower()

        if intent_value == AgentIntent.CLINIC.value:
            intent = AgentIntent.CLINIC

        elif intent_value == AgentIntent.GENERAL_DENTAL.value:
            intent = AgentIntent.GENERAL_DENTAL

        else:
            raise ValueError(
                f"Invalid router response: {response}",
            )

        return AgentDecision(
            intent=intent,
            confidence=1.0,
            reasoning=(
                "Decision generated by LLM router"
            ),
        )